using System;
using Xunit;
using Util;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using System.Text;
using System.IO;

namespace CountAndSay
{
    // https://www.geeksforgeeks.org/look-and-say-sequence/
    // 1, 11, 21, 1211, 111221, 312211, 13112221, 1113213211, ...
    // How is above sequence generated?
    // n’th term in generated by reading (n-1)’th term.
    public class Solution
    {
        public string CountAndSay(int n)
        {
            List<string> numList = new List<string>();
            numList.Add("1");
            for (var numIdx = 1; numIdx < n; numIdx++)
            {
                var lastNum = numList.Last();
                var lastI = lastNum[0];
                int count = 1;
                var strIdx = 1;
                StringBuilder sb = new StringBuilder();
                while (strIdx < lastNum.Length)
                {
                    if (lastNum[strIdx] == lastI)
                    {
                        count++;
                    }
                    else
                    {
                        sb.Append($"{count}{lastI}");
                        lastI = lastNum[strIdx];
                        count = 1;
                    }
                    strIdx++;
                }
                sb.Append($"{count}{lastI}");
                numList.Add(sb.ToString());
            }
            return numList.Last();
        }
    }

    public class Test
    {
        static public void Run()
        {
            Console.WriteLine("CountAndSay");
            int input;
            string exp, res;

            input = 1;
            exp = "1";
            using (new Timeit())
            {
                res = new Solution().CountAndSay(input);
            }
            Assert.Equal(exp, res);

            input = 4;
            exp = "1211";
            using (new Timeit())
            {
                res = new Solution().CountAndSay(input);
            }
            Assert.Equal(exp, res);

            input = 5;
            exp = "111221";
            using (new Timeit())
            {
                res = new Solution().CountAndSay(input);
            }
            Assert.Equal(exp, res);
        }
    }
}